### ISSUE TITLE
Certificate numbers fail to match

### ISSUE THREAD

**Issue by dchatters** [youngtai/gedcomx-differ-react#9]
In almost all my records the certificate numbers in the record fields don't match.  Even though they seem to be exactly the same.  The only way I can make them match is to delete one and add it back in Differ.  See attached.
[007428608_00056.left.edit.json](https://github.com/user-attachments/files/16134039/007428608_00056.left.edit.json)
[007428608_00056.right.edit.json](https://github.com/user-attachments/files/16134040/007428608_00056.right.edit.json)

**Comment by dchatters** [comment]
I guess ignore this issue.  It's an issue with just one record the one on the right.  When I edit that record in GEDCOMX and resave it all is well.  It is apparently not an issue with Differ.

**Comment by youngtai** [comment]
@dchatters Yeah I made a fix for this last week or two weeks ago. There was a typo in the GedcomX editor/viewer, where the URL created for the `type` was `http://gedcomx.com/Original` instead of `http://gedcomx.org/Original`. So you'll probably see this happen for files that were created after the typo was introduced and before the fix. The change was introduced 5/31/24, and the fix was made 6/24/24 - so almost a month's worth of files will be affected.

One thing you can do is to fix it manually at diff time, or do a search and replace for "gedcomx.com" -> "gedcomx.org"
